### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by kdlin** [OscarEngelbrektson/SyntheticControlMethods#5]
Hi Oscar,

I'd like to suggest that you add the following?

1. For in-time placebo analysis, it is desirable to have a quantitative number describing the placebo effect. Using your West Germany Reunification example, maybe you can have a rmspe number for 1982-1989 to denote the placebo effect?
2. For in-place placebo effect analysis, it would be great to have an api parameter that allows the users to exclude the treated unit. In your West German Reunification example, if the analysis can be done with and without the West Germany data, that would explain the placebo effect even more.
3. Maybe you can add a page to describe the various APIs in your package? You have examples for using them. But it would help if you have a page describing these APIs as well.
Hope this help.

**Comment by OscarEngelbrektson** [comment]
Hey @kdlin,

Once again, thanks so much for the feedback - I really appreciate it!

Responding to each of the points in order:
1. The point of the in-time placebo is to judge if the synthetic control outcome diverges from the treated unit outcome in the post-treatment period because of there being an actual treatment effect or just because we overfit to the pre-treatment period and the quality of the fit rapidly deteriorates as we move into the future/out-of-sample. I feel like this is easy to evaluate visually, and if it isn't there probably isn't much of a treatment effect (or severe overfitting). For example, I have never seen a paper put a number on the estimated placebo-treatment effect for the period between the placebo treatment and the real treatment. That said, it should be an easy addition to make so I might add it in the not so distant future.
2. For in-space placebos, the treated unit is _always_ excluded. Crucially, it should never be included in a synthetic control because it was subjected to treatment. As such, it can not be used as a control for what the outcome of some unit would have been in the absence of treatment. in_space_placebo() excludes the treated unit automatically.
3. Great point! I have extended the [user guide](https://nbviewer.jupyter.org/github/OscarEngelbrektson/SyntheticControlMethods/blob/master/examples/user_guide.ipynb) to explain both the APIs themselves and how to use/interpret them. In the future, once the package reaches something closer to stable-state, I look to develop a more rigorous documentation using something like readthedocs.com.

Best,
Oscar

**Comment by kdlin** [comment]
Hi Oscar,

Thank you very much for considering my inputs. I really appreciate it. Regarding #1, it is useful to have numerical placebo effect so that it can be presented when various scenarios are considered. Thank you very much for considering it as a feature for future release.
