### ISSUE TITLE
Hi, Sometimes sum(sc.original_data.weight_df['Weight']) ! = 1, so how can I get the right weight?

### ISSUE THREAD

**Issue by SweetBeans0126** [OscarEngelbrektson/SyntheticControlMethods#9]
First of all, I like this package!!!  I need the weight for other information, but I ran into a situation after I get the weight: When `sc.original_data.weight_df['Weight']) ! = 1`, no matter how I deal with the weight,  the sythetic control is not same as the plot.

**Comment by OscarEngelbrektson** [comment]
Hey @SweetBeans0126,

Thanks for the kind words  - I really appreciate you taking the time to ask questions!

Three points:

1. If you are just after the outcome itself, you can find it in the `original_data` object, as `original_data.synth_outcome`.  If you want to manually recompute the outcome for the synthetic control, you can use the equality:
` (sc.original_data.control_outcome_all @ sc.original_data.w).T == sc.original_data.synth_outcome`
2. Regarding the summing issue, 
`sc.original_data.w.sum()`
`>>> 1.0000000000000002`
That is, the inequality doesn't hold because of small numerical errors, but is only different at around the 16th decimal point so I haven't worried too much about it. If you have ideas about how to improve things, I'd really appreciate it.
3. Lastly, it is worth noting that the original_data.weight_df has been styled to only show units with more than 0.001 weight to improve readability. For computations, I use––and recommend that you use––original_data.w which just has the raw weights.

Generally, if you want to compute things that are not provided by default, I store all the variables in Synth.original_data.

Best,
Oscar

**Comment by SweetBeans0126** [comment]
> Hey @SweetBeans0126,
> 
> Thanks for the kind words - I really appreciate you taking the time to ask questions!
> 
> Three points:
> 
> 1. If you are just after the outcome itself, you can find it in the `original_data` object, as `original_data.synth_outcome`.  If you want to manually recompute the outcome for the synthetic control, you can use the equality:
>    ` (sc.original_data.control_outcome_all @ sc.original_data.w).T == sc.original_data.synth_outcome`
> 2. Regarding the summing issue,
>    `sc.original_data.w.sum()`
>    `>>> 1.0000000000000002`
>    That is, the inequality doesn't hold because of small numerical errors, but is only different at around the 16th decimal point so I haven't worried too much about it. If you have ideas about how to improve things, I'd really appreciate it.
> 3. Lastly, it is worth noting that the original_data.weight_df has been styled to only show units with more than 0.001 weight to improve readability. For computations, I use––and recommend that you use––original_data.w which just has the raw weights.
> 
> Generally, if you want to compute things that are not provided by default, I store all the variables in Synth.original_data.
> 
> Best,
> Oscar

Hi, @OscarEngelbrektson 
Thanks for the 3 points! 
1. With the answer, I used sc.original_data.w to calculate other information of control group and I verifed that ` (sc.original_data.control_outcome_all @ sc.original_data.w).T == sc.original_data.synth_outcome`. 
2. I tested  and it woundn't hurt the result.
3. Yeah, I should've used sc.original_data.w 
Now, all my problems is solved. Thanks again.
